feature_selection:
  encode_categoricals: true
  methods:
  - rfe
  - mutual_info
  - feature_importance
  n_features: 14
mlruns_path: mlruns
model: XGBoostClassifier
model_params:
  booster: gbtree
  colsample_bytree: 0.8
  eval_metric: logloss
  gamma: 0.1
  learning_rate: 0.1
  max_depth: 6
  n_estimators: 100
  reg_alpha: 0.01
  reg_lambda: 0.01
  subsample: 0.8

target: canceled
to_feature_store: true
train_prefix: train
use_feature_selection: true
val_prefix: val
