feature_selection:
  encode_categoricals: true
  methods:
  - rfe
  - mutual_info
  - feature_importance
  n_features: 14
mlruns_path: mlruns
model: XGBClassifier
model_params:
  colsample_bytree: 0.8
  eval_metric: logloss
  gamma: 0.1
  learning_rate: 0.001
  max_depth: 6
  n_estimators: 1000
  reg_alpha: 0.1
  reg_lambda: 0.1
  subsample: 0.8
target: canceled
to_feature_store: true
train_prefix: train
use_feature_selection: true
val_prefix: val
